### ISSUE TITLE
Use Packet Terraform Provider

### ISSUE THREAD

**Issue by frouioui** [vitessio/arewefastyet#76]
#### Description
Packet has a provider on Terraform we can use to manage instances. Where we used the Packet library before, we can now use the Terraform provider. Using it will increase task reproducibility as well as our overall confidence in the underlying infrastructure used to run tasks.

**My thought on how the complete setup should look like is:**

- [x] Having a "main" Terraform directory hosting the required configuration to run a single-node on Packet. #77 
- [x] For each task we run, copy that "main" Terraform directory to the task's build directory. #93 
- [x] Proceed to initialize Terraform in the task's build directory. #93 
- [x] Plan and Apply the configuration. #83
- [x] Later on, destroy the plan. #99 #101 

Because these steps are too numerous and broad, this issue will focus on the first step. But will be used as a reference for future issues.

**Comment by frouioui** [comment]
All related issues and pull requests closed, closing this issue.
