### ISSUE TITLE
MVP Microbenchmarks Tracking

### ISSUE THREAD

**Issue by frouioui** [vitessio/arewefastyet#80]
This issue tracks all known tasks needed to accomplish a feasible MVP of the Microbenchmarks:

- [x] Rolling update of the server #42 #97 
- [x] Microbenchmarks: use existing tests #70
- [x] Specify the instance type on which to run benchmarks #75 #85
- [x] Addition of sample Equinix Terraform create node #77
- [x] Render microbenchmarks in the UI through a table #79 #95 
- [x] Add the creation of Equinix packet devices to the Go CLI #82 #83
- [x] Link the new Go CLI to the Go WebUI #86 #90
- [x] Configure infrastructure with Ansible for Microbenchmarks #87 #89
- [x] Execute microbenchmarks on an infra with ansible in a single command #92 #93

**Comment by frouioui** [comment]
The last issue of the list fixed and merged. Closing this issue, MVP is done and accessible [here](https://benchmark.vitess.io/microbench).
